# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ede229718923206785a0ebcf388be9b15e65c966ec99fd0160e060f551275ac3524f0e3db27d532e68389abc5c46f1786ce86d6b3902f2564220a0463ba5f39

test:
  secret_key_base: 275518155ba530ec40abe2e16d686dce45486328d043d62350cbb88b8b42a109ee59a558621316e9a0e7cfe1a7cc6061a8f6a2ea520912affb60742ac9e65d04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
